### PR TITLE
chore: adding support to python 3.11

### PR DESCRIPTION
**Pull request by darkaico**
Fixes amueller/word_cloud/issues/691

* Compiled `query_integral_image` with the latest Cython
* Added python 3.11 to the CI matrix

### CODE REVIEW

**Comment by amueller** [comment]
overall looks good but I'm confused that CI is not running. was the whitespace change in the yaml necessary?

**Comment by amueller** [comment]
I'm sorry, there was an issue with the actions setup. can you please merge master into the PR?

**Comment by darkaico** [comment]
> I'm sorry, there was an issue with the actions setup. can you please merge master into the PR?

thanks for checking! I just rebased the branch with the latest master

**Comment by darkaico** [comment]
@amueller pinging you again in case you missed the update 😃

**Comment by dogancanbakir** [comment]
@darkaico Thanks for the PR.
@amueller  Is there any chance that you merge this PR anytime soon?

**Comment by amueller** [comment]
sorry for the delay. I'm surprised the CI still didn't kick off... I'm not sure what's happening there.

**Comment by dlukes** [comment]
Thank you for adding 3.11 support! Any chance of cutting a release with the fix soonish? People are failing to install the latest release on 3.11 (cf. linked issues above). The readme says that the code is tested against 3.11, which of course by no means implies that the latest release installs on 3.11, technically, but it does set up an expectation that it should work.

**Comment by mratanusarkar** [comment]
I see the support for python 3.11 is added in the PR to master. But pip install still doesn't pull the latest changes.
pip install is still failing for python 3.11, so any tentative date for the next release with the fix?

**Comment by amueller** [comment]
Sorry for the slow response, there were a lot of issues on this. I shipped a release in April.

**Comment by JamesStallings** [comment]
Apparently, it didn't work. I'm on debian 12, attempting to build wordcloud 1.8.1 as part of a dependencies requirement.

**Pull request merged**
