### PR TITLE
Fix install

### PR DESCRIPTION
**Pull request by remram44**
* Unify your requirements
* Add version constraint for numpy for pip and conda
* Fix conda recipe (did this build before without the `--single-version-externally-managed` trick?)

I'm not sure you want matplotlib to be a hard requirement since you went to the trouble of not having it be a top-level import.

### CODE REVIEW

**Comment by amueller** [comment]
thanks. how about we get rid of requirements.txt?

**Comment by remram44** [comment]
Done!

**Comment by amueller** [comment]
sweet!

**Comment by amueller** [comment]
oh you need to fix the travis script now, I guess...

**Comment by amueller** [comment]
thanks!

**Pull request merged**
