### PR TITLE
Add Bounding Box Scaling Method

### PR DESCRIPTION
**Pull request by Will-Renius**
I added bounding boxes for word sizes to the layout and used these to adjust font size so they don't scale to overlap other words.

### CODE REVIEW

**Comment by Will-Renius** [comment]
Any interest in merging this feature? I was hoping to get improved scaling into the source code rather than maintaining it separately for my applications. I'm open to other ideas for fixes.

**Comment by amueller** [comment]
Sorry I was busy and didn't see this. Can you explain what the goal is?

**Comment by Will-Renius** [comment]
The goal is to prevent overlapping words when using scale. 

The current scaling method uses the same value to adjust image size and font size. However, fonts don't scale at 1:1 with pixel width. This change keeps the original bounding box used to place the word, scales that, then limits the font to stay within the new bounding box.

**Comment by amueller** [comment]
hm that makes sense.
Would that be solved better by not using scaling and export vector graphics directly, see #58

**Comment by Will-Renius** [comment]
Hard to say, my goal is to keep image size low when computing and then increase resolution in order to speed up processing, which is exactly what the scaling mechanism is there for. If a proper vector graphic implementation is implemented would you want to replace the current scaling mechanism with one that relies on conversion of vector graphics to a PIL image?

**Comment by amueller** [comment]
Yes that's what scaling is for, but it's a bit of a hack. If we have vector graphics support, why would you convert to a PIL image? You could convert the vector graphic to PNG in the end if you wanted to, I guess.

**Pull request closed without merging**
