### PR TITLE
Example bigrams

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by erfelipe** [comment]
Hi, 
Is it possible to use bigrams in text with some separator to produce a word cloud?

**Comment by amueller** [comment]
Hi. Can you please explain what you mean by that?

**Comment by erfelipe** [comment]
Example:  "cat white dog black cat white" ...  I prepare the file for: "cat white, cat white, dog black"  and I looking for a cloud for "cat white" (increase size) and "dog black" (decrease size) like bigrams. Is it possible? or only for individual tokens.  Regards!

**Comment by amueller** [comment]
With the ``generate_from_frequencies`` method you can do anything you'd like. For example you could pass it tokens from splitting your string by ``","``.

**Pull request merged**
