### PR TITLE
Add an example for Arabic

### PR DESCRIPTION
**Pull request by AMR-KELEG**
Adapted from #315

### CODE REVIEW

**Comment by AMR-KELEG** [comment]
@amueller Hi Andreas, could you please review and merge the PR into master?
Thanks

**Comment by amueller** [comment]
Thanks, sorry for the delay. Could you say what the text is?
Also weirdly there is no preview for the docs in the CI. Not sure why that is, but looks good and the example seems to be running in sphinx-gallery.

**Comment by AMR-KELEG** [comment]
The text was part of the original PR and it's the Wikipedia article about the Arabic language https://ar.m.wikipedia.org/wiki/%D8%A7%D9%84%D9%84%D8%BA%D8%A9_%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9

For the docs preview, I am not sure how can I fix it.

**Comment by amueller** [comment]
Ok great, thanks!

**Pull request merged**
