### PR TITLE
Fix the script test.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by amueller** [comment]
have you tested that locally? For some reason travis didn't fail on the other branch.

**Comment by amueller** [comment]
fails now ^^

**Comment by xuhdev** [comment]
@amueller My guess is that travis made some changes somehow. wordcloud_cli.py was in PATH a few days ago, but now it's not.

**Comment by xuhdev** [comment]
@amueller All tests have passed now. Can you also release a new version to PyPI after merging? People who install from PyPI now are experiencing CLI issues...

**Pull request merged**
