### PR TITLE
setup: Simplify release process using "versioneer"

### PR DESCRIPTION
**Pull request by jcfr**
Release process is now as simple as tagging a release, there
is no need to manually updates version in __init__.py

Most of the files enabling this process have been generated and/or
updated after:
1) pip install versioneer
2) adding "versioneer" section to setup.cfg
3) running "versioneer install"

For more details, see https://github.com/warner/python-versioneer/

### CODE REVIEW

**Comment by amueller** [comment]
I still haven't figured out how to do a release with this, and there's no information about how to do that in the documentation of versioneer and I couldn't find anything on google. I think it would be great to release. Can you tell me how to do that?

**Comment by jcfr** [comment]
> Can you tell me how to do that?

See https://github.com/amueller/word_cloud/blob/master/doc/make_a_release.rst

**Comment by jcfr** [comment]
Before releasing, CI should be green on all platforms. Last merge to master reported failure on linux, see https://circleci.com/gh/amueller/word_cloud/925

**Comment by amueller** [comment]
Thanks!

**Comment by jcfr** [comment]
If you haven't address the linux issue, I could have a look in the next few days. Let me know.

**Comment by amueller** [comment]
should by fixed by #500

**Pull request merged**
