### PR TITLE
Fix some deprecated

### PR DESCRIPTION
**Pull request by teriterance**
This pull request remove some warning for deprecated variables

`lib/python3.8/site-packages/wordcloud/wordcloud.py:501: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.`
I used textlength in place of textsize

np.int is a deprecated, replaced by int. 

and ROTATE_90 replaced by Transpose.ROTATE_90

### CODE REVIEW

**Comment by amueller** [comment]
Thank you for the PR! This looks good but I'd like to make sure the tests run. It seems I messed up my CI (again?), and I need to double check what the issue is.

**Comment by teriterance** [comment]
That was my own error, I will fix that today.

**Comment by teriterance** [comment]
the tests have good results except for 2 of them due to the difference between textsize and textbox
https://stackoverflow.com/questions/65494932/imagedraw-adapt-font-size-dynamically-to-text-length:

test/test_wordcloud.py:255: in test_mask
    assert_array_equal(wc_array[mask != 0], 0)
E AssertionError:
E Arrays are not equal
E
E Mismatched elements: 14853 / 15000 (99%)
E Max absolute difference: 239
E Max relative difference: less
E x: array([[ 32, 163, 134],
E [32, 163, 134],
E [ 32, 163, 134],...
E y: array(0)
____________________________________________________________________________________________ test_mask_contour ____________________________________________________________________________________________
test/test_wordcloud.py:281: in test_mask_contour
    assert lg_total > sm_total
E assert 1369086 > 1643735

**Comment by kaisugi** [comment]
any updates?

**Comment by teriterance** [comment]
I changed the mask value because ImageDraw.textbbox() and ImageDraw.textsize() don't give the same image

for example with textsize()
image

and for example with textbbox()
image

**Comment by amueller** [comment]
Thanks. Did you see CI running? I'm confused they didn't seem to be running now. Maybe merge in the master branch? I'll try to check it later this week but pretty busy right now.

**Comment by alexlang74** [comment]
Hi all - any timeline to get this released?

**Comment by amueller** [comment]
the timeline is mostly me trying to get CI to work again. Can you please try and merge master and push to the branch?

**Comment by amueller** [comment]
hm reopening didn't trigger it apparently

**Comment by amueller** [comment]
I think I'll merge in #711 which contains some further fixes, thanks for your help!

**Pull request closed without merging**
