### PR TITLE
Frequency scaling

### PR DESCRIPTION
**Pull request by amueller**
Finally actually taking the relative frequencies into account.

### CODE REVIEW

**Comment by amueller** [comment]
just using the ratios (i.e. ``relative_scaling=1``) doesn't look good because it doesn't fill the space. I played around with several non-linear functions of the ratio, and doing ``(new_freq / old_freq) ** (1. / some_number)`` looks similar. But just having a linear function seems more easy to understand.

**Comment by pcrutchl** [comment]
Great, thanks. Trying out now instead of my hacky version.

**Comment by amueller** [comment]
well this is also pretty hacky, but I am not sure what else I could be doing. Play around with ``relative_scaling`` around ``.5`` and ``max_font_size``.

**Comment by amueller** [comment]
Feel free to post pictures ;)

**Pull request merged**
