### PR TITLE
add unicode support for stopwords

### PR DESCRIPTION
**Pull request by icyblade**
Trying to solve https://github.com/amueller/word_cloud/issues/253

### CODE REVIEW

**Comment by amueller** [comment]
Maybe use
```python
stopwords = set([x.lower() for x in self.stopwords])
```
instead?
Also please add a non-regression test

**Comment by amueller** [comment]
happy to merge this if you can add a test :)

**Comment by icyblade** [comment]
Before PR:

    $ python -c "from wordcloud import WordCloud; print(WordCloud(stopwords=[u'test']).generate(u'this is a test of this software'))"
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/wordcloud/wordcloud.py", line 556, in generate
        return self.generate_from_text(text)
      File "/usr/lib64/python2.7/site-packages/wordcloud/wordcloud.py", line 541, in generate_from_text
        words = self.process_text(text)
      File "/usr/lib64/python2.7/site-packages/wordcloud/wordcloud.py", line 506, in process_text
        stopwords = set(map(str.lower, self.stopwords))
    TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
    $
    
After PR:

    $ python -c "from wordcloud import WordCloud; print(WordCloud(stopwords=[u'test']).generate(u'this is a test of this software'))"
    <wordcloud.wordcloud.WordCloud object at 0x7f69d930e910>
    $

**Comment by amueller** [comment]
Please add that to ``test/test_wordcloud.py`` as a separate test.

**Comment by amueller** [comment]
Thanks. Unfortunately this test doesn't pass on Python 3 because there is no ``unicode`` type.
We could either skip this test on python3 or try to make it compatible.

**Comment by icyblade** [comment]
As I have no py3 environment, I gotta deal with this problem tomorrow.

**Comment by amueller** [comment]
no worries, thanks for your help!

**Comment by amueller** [comment]
Thanks :)

**Pull request merged**
