### PR TITLE
build python3.8, windows build 32bit

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by amueller** [comment]
@jcfr some weird errors on Python3.8 if you have a minute :-/
First it was failing in numpy because it couldn't find the multiarray so file, then it failed in flake8?

**Comment by jcfr** [comment]
Having a look now.

I will split the updates in few PRs:
* flake8 issue by pinning the version.
* then add python 3.8 for 64-bit
* then add 32-bit build support

**Comment by jcfr** [comment]
> flake8 issue by pinning the version.

This will be addressed in #546

**Comment by jcfr** [comment]
> then add python 3.8 for 64-bit

See https://github.com/amueller/word_cloud/pull/547

**Comment by jcfr** [comment]
> then add 32-bit build support

See https://github.com/amueller/word_cloud/pull/549

**Comment by jcfr** [comment]
Closing. This PR is now obsolete

**Comment by amueller** [comment]
Awesome, thank you so much!

**Pull request closed without merging**
