### PR TITLE
remove python3.4 from AppVeyor, CircleCI and Travis

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by amueller** [comment]
@jcfr do you know what's happening with circle? Seems related to scikit-ci and pytest. I have no idea what's happening there.

**Comment by jcfr** [comment]
The issue reported on CircleCI is due a regression in pytest. See https://github.com/Teemu/pytest-sugar/issues/187

The regression  was introduced in pytest 5.4.0, and then later fixed in 5.4.1. See https://github.com/Teemu/pytest-sugar/issues/187 and https://github.com/pytest-dev/pytest/releases/tag/5.4.1

For future reference, here is the error copied from [CircleCI](https://app.circleci.com/pipelines/github/amueller/word_cloud/2/workflows/564cce2a-fe79-4e87-9813-778485b8e1cc/jobs/1238):

```
[scikit-ci] Executing: pytest
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/_pytest/main.py", line 187, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/_pytest/config/__init__.py", line 820, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pytest_sugar.py", line 176, in pytest_configure
INTERNALERROR>     sugar_reporter = SugarTerminalReporter(standard_reporter)
INTERNALERROR>   File "/opt/python/cp35-cp35m/lib/python3.5/site-packages/pytest_sugar.py", line 214, in __init__
INTERNALERROR>     self.writer = self._tw
INTERNALERROR> AttributeError: can't set attribute

```

**Comment by jcfr** [comment]
I will create a separate PR addressing the problem, once merged I will rebase this topic.

**Comment by amueller** [comment]
Thanks for checking it out! I saw the failure but didn't expect it to be actually in pytest, I didn't check out pytest sugar. Thanks again!

**Pull request merged**
