### PR TITLE
Add continuous integration support for building, testing and uploading wheels

### PR DESCRIPTION
**Pull request by jcfr**
This commit adds support for Linux, macOS and Windows wheels.

* use scikit-ci: Simpler and centralized CI configuration for Python extensions.
  See http://scikit-ci.readthedocs.io

* use scikit-ci-addons: set of scripts useful to help drive CI.
  See http://scikit-ci-addons.readthedocs.org/

* circleci: use manylinux dockcross images including scikit-build, cmake and ninja.

### CODE REVIEW

**Comment by amueller** [comment]
awesome, thank you so much!
There's a python27 failure but that might be unrelated?

I'm still sprinting on scikit-learn but I'll look at this asap.

**Comment by jcfr** [comment]
> I'm still sprinting on scikit-learn but I'll look at this asap.

:+1: 

> There's a python27 failure but that might be unrelated?

Strange. The previous build based of [04336af](https://github.com/amueller/word_cloud/commit/1f30a0e0dfda17062f03415446d470a3803c3721) was successful. See https://ci.appveyor.com/project/amueller/word-cloud/build/0.0.1.36/job/8omykio142aikuih

I will re-trigger the build amending the last commit

**Comment by jcfr** [comment]
@amueller Green it is :fireworks:

**Comment by jcfr** [comment]
@amueller  Let me know how I could help ? I would love to move forward with this. 

Let me now what you think:

* If you add me as a maintainer (username `jcfr`) of the package on PyPi, I could generate the secure env variable and that would make things easier on your side.

* If you add me as a collaborator on GitHub, I would merge the PR, push a tag and ensure wheels are uploaded.

Best, 
Jc

**Comment by amueller** [comment]
hey @jcfr sorry for being slow. Trying to get an sklearn release out the door. done.

**Comment by jcfr** [comment]
No problem. Good luck with the sklearn release :smile:  and ping me back on you have some more time to move this forward.

**Comment by jcfr** [comment]
Thanks for adding me to pypi and the project, I will finalize this topic later tonight.

**Comment by jcfr** [comment]
Closing. Change integrated in https://github.com/amueller/word_cloud/commit/9d0eb90d5ed0e62d01708ff5cee817cb1c7c0ea7

**Pull request merged**
